# Generated by Django 2.2.3 on 2019-07-14 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'blank': 'Este campo no esta completo, intentalo otra vez', 'unique': 'Este titulo no es unico, intentalo otra vez'}, help_text='El titulo debe ser unico', max_length=240, unique=True, verbose_name='Post title'),
        ),
    ]
